// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtAiPRpR8Hz8ifxVzQEK1Lz_70yfINYrw',
    appId: '1:1098971471552:web:c62a3dbc771756e6291725',
    messagingSenderId: '1098971471552',
    projectId: 'bizmatic-solution',
    authDomain: 'bizmatic-solution.firebaseapp.com',
    storageBucket: 'bizmatic-solution.firebasestorage.app',
    measurementId: 'G-H53CX46TTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjARSw6FkZGysxkVvwaMN7BwpYYACmWL0',
    appId: '1:1098971471552:android:e9726668b7d4c85d291725',
    messagingSenderId: '1098971471552',
    projectId: 'bizmatic-solution',
    storageBucket: 'bizmatic-solution.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqQ34f8QmI3ObYWTz9PSxjmI1I1ZmbCTQ',
    appId: '1:1098971471552:ios:bfb7e007aad6a1b8291725',
    messagingSenderId: '1098971471552',
    projectId: 'bizmatic-solution',
    storageBucket: 'bizmatic-solution.firebasestorage.app',
    iosBundleId: 'com.example.bizmaticSolutions',
  );
}
